name: Test GitAction
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - run: echo "ğŸ‰ Le travail a Ã©tÃ© automatiquement dÃ©clenchÃ© ${{ github.event_name }}."
            - run: echo "ğŸ§ Ce travail s'exÃ©cute dÃ©sormais sur un serveur ${{ runner.os }} hÃ©bergÃ© par GitHub!"
            - run: echo "ğŸ” Le nom de votre branche est ${{ github.ref }} et votre rÃ©fÃ©rentiel est ${{ github.repository }}."
            - name: Check out repository code
              uses: actions/checkout@v5
            - run: echo "ğŸ’¡ Le rÃ©fÃ©rentiel ${{ github.repository }} Ã  Ã©tÃ© clonÃ©."
            - run: echo "ğŸ–¥ï¸ Le workflow est maintenant prÃªt Ã  tester votre code sur le coureur."
            - name: List files in the repository
              run: |
                ls ${{ github.workspace }}
            - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."